on:
  push:
jobs:
   build: 
     runs-on: ubuntu-latest
     steps: 
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: post changeset to ConnectALL
        run: | 
          perl .github/scripts/push-changeset.pl
        env:
          CONNECTALL_APPLINK_NAME: GithubCommitLog
          CONNECTALL_PROJECT_KEY: DEMO
          CONNECTALL_BASE_URL: ${{ secrets.CONNECTALL_URL }}
          CONNECTALL_USER: ${{ secrets.CONNECTALL_USER }}
          CONNECTALL_PASSWORD: ${{ secrets.CONNECTALL_PASSWORD }}
          GITHUB_EVENT_BEFORE: ${{ github.event.before }}
          GITHUB_EVENT_AFTER: ${{ github.event.after }}
          